spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/IMS?serverTimezone=GMT%2b8&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  mvc:
    static-path-pattern: /static/**
  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
#  redis:
#    host: 127.0.0.1
#    port: 6379
server:
  context-path: /IMS


logging:
  pattern:
    console: "%d - %msg%n"
  file: ims.log


